### ISSUE TITLE
trouble installing extension

### ISSUE THREAD

**Issue by GDRepo** [kkrisz1/staruml-reverse-db#33] opened 2018-07-30 14:57 UTC
Hello,
My client and I are very interested in using the staruml-reverse-db extension but the extension keeps showing "Extension error" in Extension Manager and the database menu items to configure server etc are not functioning. I did also try installing the extension manually by copying the folder to the extensions folder but am getting the same outcome. I'm using a freshly downloaded copy of staruml 3.0.1 (unregistered). Do you have any suggestions? 
Thanks!

**Comment by kkrisz1** [comment] 2018-07-30 21:57
Hi,
Could you check the console output?

1. open `Debug > Show DevTools (alt+shit+t)`
2. reload StarUML with `ctrl+r`

**Comment by GDRepo** [comment] 2018-07-31 14:11
Hello,

Thanks for your reply. This is the message I see in the Console after following the steps above: 

C:\Program Files\StarUML\resources\app.asar\src\extensibility\extension-loader.js:205 [Extension] failed to load C:\Users\gdauphin\AppData\Roaming\StarUML\extensions\user\kkrisz1.staruml-reverse-db Error: Cannot find module 'tedious-connection-pool'

Thanks for your help!

**Comment by kkrisz1** [comment] 2018-08-01 09:12
Could you execute the below steps?

1. Remove `C:\Users\gdauphin\AppData\Roaming\StarUML\extensions\user\kkrisz1.staruml-reverse-db`
2. [Download](https://github.com/kkrisz1/staruml-reverse-db/releases/download/v1.0.6/kkrisz1.staruml-reverse-db-1.0.6.zip) the latest release
3. Extract it to `C:\Users\gdauphin\AppData\Roaming\StarUML\extensions\user`
4. (Re)start StarUML

Please let me know the result.

**Comment by GDRepo** [comment] 2018-08-01 15:06
Hello again, 
Still same result after deleting and reloading. I also went a step further and completely un-installed StartUML, deleted the StarUML folder completely, re-installed StarUML with a fresh download from this morning, then copied the reverse-db exension (also downloaded this morning) to the extensions folder. I tried the "debug/Show DevTools/console" steps again and am seeing the same "Cannot find module 'tedious-connection-pool" error. I should also mention, I had 2 other people try the install as well and none have been able to install the reverse-db extension. We're all using Windows 10 I believe. Any other ideas? Perhaps the'tedious-connection-pool' has been deprecated?
Thanks again!

**Comment by kkrisz1** [comment] 2018-08-05 18:24
I have no clue why the extension was not installed.
I asked some help from the StarUML support.
Please see below the answer:

> Hi,
> 
> I successfully installed your extension in Windows 10. I can see all menu items and can show preference dialogs when click configure menu item. There is no errors in console.
> 
> Thanks,

**Comment by kkrisz1** [comment] 2018-10-06 23:44
Release v1.0.9 is coming soon.
Please try it.
I close the issue. I cannot reproduce it.

**Closed by kkrisz1** 2018-10-06 23:44 UTC
