### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'hasPrecision')

### ISSUE THREAD

**Issue by InterinfoDev** [kkrisz1/staruml-reverse-db#81] opened 2022-06-14 04:42 UTC
Hi , i am using starUML to design E-R Model，
and installed the extension "Entity Relationship DataModel Generation"

my database  is MS-SQL and version between 2016 and 2019.
i am getting some problem when i want to import schema..

the debug console message show :

Uncaught TypeError: Cannot read properties of undefined (reading 'hasPrecision')
    at readPrecision (rootPathAppData\Roaming\StarUML\extensions\user\kkrisz1.staruml-reverse-db\node_modules\tedious-connection-pool\node_modules\tedious\lib\metadata-parser.js:45)
    at rootPathAppData\Roaming\StarUML\extensions\user\kkrisz1.staruml-reverse-db\node_modules\tedious-connection-pool\node_modules\tedious\lib\value-parser.js:456
    at rootPathAppData\Roaming\StarUML\extensions\user\kkrisz1.staruml-reverse-db\node_modules\tedious-connection-pool\node_modules\tedious\lib\token\stream-parser.js:162
    at Parser.awaitData (rootPathAppData\Roaming\StarUML\extensions\user\kkrisz1.staruml-reverse-db\node_modules\tedious-connection-pool\node_modules\tedious\lib\token\stream-parser.js:136)
    at Parser.readUInt8 (rootPathAppData\Roaming\StarUML\extensions\user\kkrisz1.staruml-reverse-db\node_modules\tedious-connection-pool\node_modules\tedious\lib\token\stream-parser.js:159)
    at rootPathAppData\Roaming\StarUML\extensions\user\kkrisz1.staruml-reverse-db\node_modules\tedious-connection-pool\node_modules\tedious\lib\value-parser.js:453
    at rootPathAppData\Roaming\StarUML\extensions\user\kkrisz1.staruml-reverse-db\node_modules\tedious-connection-pool\node_modules\tedious\lib\token\stream-parser.js:162
    at Parser.awaitData (rootPathAppData\Roaming\StarUML\extensions\user\kkrisz1.staruml-reverse-db\node_modules\tedious-connection-pool\node_modules\tedious\lib\token\stream-parser.js:136)
    at Parser.readUInt8 (rootPathAppData\Roaming\StarUML\extensions\user\kkrisz1.staruml-reverse-db\node_modules\tedious-connection-pool\node_modules\tedious\lib\token\stream-parser.js:159)
    at rootPathAppData\Roaming\StarUML\extensions\user\kkrisz1.staruml-reverse-db\node_modules\tedious-connection-pool\node_modules\tedious\lib\value-parser.js:452

so how can i to fix the problem?

thanks

**Comment by kkrisz1** [comment] 2022-07-24 23:35
hi,
could you try with the version [v2.1.1](https://github.com/kkrisz1/staruml-reverse-db/releases/download/v2.1.1/kkrisz1.staruml-reverse-db-2.1.1.zip)?

**Comment by kkrisz1** [comment] 2023-05-31 07:07
Cannot reproduce. I close the issue.

Feel free to reopen if the problem occures again

**Closed by kkrisz1** 2023-05-31 07:07 UTC
